version: '3'
services:
  backend:
    build: ./backend/mypjt
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: development
  
  frontend:
    build: ./frontend/mypjt
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production  
    volumes:
      - ./frontend/mypjt:/app 
      - /app/node_modules